services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - default

  hasura:
    image: hasura/graphql-engine:v2.36.1
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true" # set to "false" to disable access control
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey # set this to secure your endpoints
    networks:
      - default

  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    depends_on:
      - db
      - hasura
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/postgres
      "HASURA_URL": "http://hasura:8080"
      "HASURA_GRAPHQL_ADMIN_SECRET": "myadminsecretkey"
    networks:
      - default

volumes:
  postgres-data:
