name: Test run
on:
  push:
    branches:
      - master
      - playground-*
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # nodeVersion: [20, 22]
        # typeormVersion: [0.3.12, 0.3.14 , 0.3.17, 0.3.19, 0.3.20, latest]
        nodeVersion: [20]
        typeormVersion: [0.3.12, 0.3.14]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: "Install"
        run: npm install --no-save typeorm@${{ matrix.typeormVersion }}
      - name: "Build"
        run: npm run build
      - name: "Test"
        run: npm run test
